#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'git',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git'
