#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'postgresql'
cookbook 'git'
cookbook 'nginx'
cookbook 'unicorn'
cookbook 'rvm', git: 'git@github.com:fnichol/chef-rvm.git'

##
# Use this cookbook for Redis - configuration in roles[web-server] is
# tuned for it. Other cookbooks need different configution. --dk
#
cookbook 'redis', git: 'git@github.com:dmytro/chef-redis.git'

### ##
### # For Elasticsearch Java cookbook is requried
### #
### cookbook 'java',
###    :git => 'https://github.com/opscode-cookbooks/java'
### cookbook 'elasticsearch',
### #  :git => 'git://github.com/gosquared/elasticsearch-cookbook.git'
###   :git => 'git@github.com:elasticsearch/cookbook-elasticsearch.git'
### cookbook 'munin',
###    :git => 'git@github.com:dmytro/munin-solo.git'
### 
### cookbook 'git_committer',
###    :git => 'git@github.com:dmytro/git_committer.git'
cookbook 'github_keys', git: 'git@github.com:dmytro/github_keys.git'

##
# chef-solo-search is cookbook that provides support for searchable
# databags in Chef Solo
cookbook 'chef-solo-search', git: 'https://github.com/edelight/chef-solo-search.git'

### 
### # cookbook 'chef-client'
### 
### cookbook 'imagemagick'
### 
### cookbook 'apache2', '>= 1.0.0'
### 
# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
