#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'postgresql'
cookbook 'git'
cookbook 'nginx'
cookbook 'unicorn'
cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git'
### ##
### # For Elasticsearch Java cookbook is requried
### #
### cookbook 'java',
###    :git => 'https://github.com/opscode-cookbooks/java'
### cookbook 'elasticsearch',
### #  :git => 'git://github.com/gosquared/elasticsearch-cookbook.git'
###   :git => 'git@github.com:elasticsearch/cookbook-elasticsearch.git'
### cookbook 'munin',
###    :git => 'git@github.com:dmytro/munin-solo.git'
### 
### cookbook 'git_committer',
###    :git => 'git@github.com:dmytro/git_committer.git'
### cookbook 'github_keys',
###    :git => 'git@github.com:dmytro/github_keys.git'
### 
### cookbook 'chef-solo-search',
###    :git => 'https://github.com/edelight/chef-solo-search.git'
### 
### # cookbook 'chef-client'
### 
### cookbook 'imagemagick'
### 
### cookbook 'apache2', '>= 1.0.0'
### 
# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
